datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.default.svc.cluster.local

sidecar:
  dashboards:
    enabled: true
    searchNamespace: default
