---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wolverine
data:
  config.yaml: |
    urls:
      - https://httpstat.us/503
      - https://httpstat.us/200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wolverine
  name: wolverine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wolverine
  template:
    metadata:
      labels:
        app: wolverine
    spec:
      containers:
      - image: wolverine:0.1.0
        name: wolverine
        volumeMounts:
        - name: wolverine
          mountPath: "/config"
      volumes:
      - name: wolverine
        configMap:
          name: wolverine
